name: mybinder-env  # Specify the name of the environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8  # Specify the Python version
  - jupyterlab  # OR jupyter-notebook
  - thebe  # For Thebe integration
  - numpy  # Add other packages as needed
  - pandas
  - matplotlib
  - scikit-learn
  # Add any other dependencies needed for your project

