name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.8
  - numpy=1.24.3
  - matplotlib=3.7.1
  - pandas=2.0.1
  - scikit-learn=1.2.2
  - pip
  - pip:
      - jupyterlab==3.6.0
      - thebe==0.0.2
      - torch==2.0.1
    


