name: mybinder-env  # Specify the name of the environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Specify the Python version
  - jupyterlab  # OR jupyter-notebook
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  # Add any other conda dependencies here
  - pip
  - pip:
      - thebe==0.2.0  # For Thebe integration
      # Add any other pip dependencies here
