name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.0
  - matplotlib=3.9.0
  - pytorch=2.3.0
  - torchvision=0.18.0
  - pytorch-lightning=1.9.5
  - tensorboard=2.16.2
  - pip
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - arrow==1.3.0
      - jupyter
      - jupyterlab
      - nbconvert
      - jupyter-client
      - jupyter-server
      - ipykernel
      - notebook
      - matplotlib
      - scikit-learn
      - pandas
      - pytorch-lightning-bolts==0.3.2.post1
      - thebe==0.0.2
      - torchmetrics
      - torch
      - torchvision
